apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.namespace }}-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.namespace }}-{{ .Values.name }}
          servicePort: 80